# Generated by Django 4.0.2 on 2022-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='screenshot',
            field=models.ImageField(default=None, upload_to='photos/'),
        ),
    ]
