# Generated by Django 4.0.2 on 2022-02-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='screenshot',
        ),
    ]
