# Generated by Django 4.0.2 on 2022-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
